### ISSUE TITLE
Smooth scrolling not working in nano (and possibly other apps)

### ISSUE THREAD

**Issue by knuxify** [bisqwit/that_terminal#1]
Expected behavior: [1](https://i.imgur.com/SNli5Hr.gif)

What actually happens: [2](https://i.imgur.com/wINr8BD.gif)

Instead of refreshing the entire screen, it only refreshes the last line.

**Comment by bisqwit** [comment]
How do you enable smooth scrolling in Nano? (EDIT: Found it. Option `-S`)
