### ISSUE TITLE
Do not depend on PHP, please

### ISSUE THREAD

**Issue by extrowerk** [bisqwit/that_terminal#12]
I tried to build that_terminal on Haiku, and after patching the sources here and there, i was greeted with a "php: command not found" error. Please, do not depend on PHP, or at least provide the precompiled/packed fonts as binary blob in the source tree, so we can build it without php.

**Comment by bisqwit** [comment]
The pre-built fonts file (`rendering/fonts.inc`) _is_ in fact included in the repository.

If you want to force `make` not attempt to rebuild it, do `touch rendering/fonts.inc` to make sure its timestamp is newer than that of its dependencies.

**Comment by extrowerk** [comment]
> The pre-built fonts file (`rendering/fonts.inc`) _is_ in fact included in the repository.
> 
> If you want to force `make` not attempt to rebuild it, do `touch rendering/fonts.inc` to make sure its timestamp is newer than that of its dependencies.

Cool, will try!

**Comment by bisqwit** [comment]
Note that if you already attempted the `make` rule unsuccessfully, you may need to freshly re-checkout the fonts.inc file with: `git checkout HEAD rendering/fonts.inc`

**Comment by extrowerk** [comment]
Kiitos, i noticed that already.

**Comment by extrowerk** [comment]
It is actually almost working:
![iiNT](https://user-images.githubusercontent.com/5569059/73917155-24b4bf00-48bf-11ea-99ed-f727addb0d81.png)
