### ISSUE TITLE
The "ENTER" key did "Undo" action in Joe's editor when I was using that terminal

### ISSUE THREAD

**Issue by meiosischen** [bisqwit/that_terminal#14]
I'm not sure what's wrong. I ran it under archlinux, the ENTER key did wrong action in Joe. Then I had installed xterm, I found the same thing's happened.How could I fix it? Thanks

**Comment by meiosischen** [comment]
I think My ENTER key cannot transfer to that terminal correctly, The Joe’s editor didnot recognize it, but Undo was mapping to ^_，how could ENTER key be transfered to it? thanks.

**Comment by bisqwit** [comment]
Insufficient information. It works for me. Maybe you have a peculiar keyboard / operating system / window system setup.

**Comment by meiosischen** [comment]
Thanks for reply. Finally, I found that one line of joerc configuration error caused this problem
“undo        ^-      Undo changes” . I added it When I realized I had to use 'CTRL + Shift + -' to make UNDO.
ENTER worked after I removed this line.
